FROM nginx:latest
COPY   default.conf /etc/nginx/conf.d/default.conf
COPY   apache-selfsigned.key /etc/ssl/private/apache-selfsigned.key
COPY   apache-selfsigned.crt /etc/ssl/certs/apache-selfsigned.crt
VOLUME /var/log/nginx/log/
EXPOSE 443

